version: '3'
services:
  adaptive-logger-harvester:
    image: adaptive-logger-harvester
    container_name: adaptive-logger-harvester
    networks:
      - synonyms-search_default
    environment:
      - ELASTICSEARCH_URL=https://es01:9200
      - ELASTICSEARCH_CA_CERT=/app/ca.crt
      - ELASTICSEARCH_USER=elastic
      - ELASTICSEARCH_PASSWORD=elastic123
      - CONTAINER_NAME_PATTERN=kibana
      - TIME_SINCE_IN_MIN=5
      - ENV="staging"
      - APP_NAME="kibana"
      - INDEX_NAME="test4_new"
    volumes:
      - /Volumes/project/Docker-X/elastic-stack/synonyms-search/certs/ca/ca.crt:/app/ca.crt
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  synonyms-search_default:
    external: true